project:
  type: book
  output-dir: _book

book:
  title: "Modern Authoring Template"
  author: "Technical Creator"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
